### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Sequential

### ISSUE THREAD

**Issue by abcp4** [qfgaohao/pytorch-ssd#23]
Heelo, I have tried to train with mobile net networks, but the following error emerged:

2018-12-08 19:07:35,187 - root - INFO - Use Cuda.
2018-12-08 19:07:35,187 - root - INFO - Namespace(balance_data=False, base_net='/content/pytorch-ssd/models/mb2-ssd-lite-mp-0_686.pth', base_net_lr=None, batch_size=4, checkpoint_folder='models/', dataset_type='voc', datasets=['/content/MangaVOC'], debug_steps=100, extra_layers_lr=None, freeze_base_net=False, freeze_net=False, gamma=0.1, lr=0.001, mb2_width_mult=1.0, milestones='80,100', momentum=0.9, net='mb2-ssd-lite', num_epochs=1, num_workers=4, pretrained_ssd=None, resume=None, scheduler='cosine', t_max=200.0, use_cuda=True, validation_dataset='/content/MangaVOC', validation_epochs=5, weight_decay=0.0005)

2018-12-08 19:07:35,189 - root - INFO - Prepare training datasets.
2018-12-08 19:07:35,194 - root - INFO - Stored labels into file models/voc-model-labels.txt.
2018-12-08 19:07:35,194 - root - INFO - Train dataset size: 15761
2018-12-08 19:07:35,195 - root - INFO - Prepare Validation datasets.
2018-12-08 19:07:35,196 - root - INFO - validation dataset size: 3153
2018-12-08 19:07:35,196 - root - INFO - Build network.
2018-12-08 19:07:35,333 - root - INFO - Init from base net /content/pytorch-ssd/models/mb2-ssd-lite-mp-0_686.pth
Traceback (most recent call last):
  File "train_ssd.py", line 287, in <module>
    net.init_from_base_net(args.base_net)
  File "/content/pytorch-ssd/vision/ssd/ssd.py", line 112, in init_from_base_net
    self.base_net.load_state_dict(torch.load(model, map_location=lambda storage, loc: storage), strict=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Sequential:
	Missing key(s) in state_dict: "0.0.weight", "0.1.weight", "0.1.bias", "0.1.running_mean", 
        ....

The VGG network works fine to me. I believe it might be something to do with pytorch version, but I am using the latest one from pytorch website.

**Comment by qfgaohao** [comment]
@abcp4 plz try to replace '--base_net' with '--pretrained_ssd' in your command, as you are using a pretrained ssd to initialize the model. '--base_net' expects a pretained base net model, as it only initialises the base net. '--pretrained_ssd' uses pretrained weights to initialise all layers except the prediction head.

**Comment by abcp4** [comment]
It worked now!! Thank you very much!

**Comment by zhanglaplace** [comment]
@qfgaohao using --pretrained_ssd finetuning model ,the loss is not match the pretrain model. 
![image](https://user-images.githubusercontent.com/12178974/62001122-60eeb200-b11b-11e9-94cc-168c47feb710.png)
