### ISSUE TITLE
Error in retrain mb2-ssd-lite on open_images

### ISSUE THREAD

**Issue by dienhoa** [qfgaohao/pytorch-ssd#27]
I ran into a problem when try to retrain the mb2-ssd-lite model with open images data set.

The command I used:
`python train_ssd.py --dataset_type open_images --datasets ~/data/open_images --net mb2-ssd-lite --pretrained_ssd models/mb2-ssd-lite-mp-0_686.pth --scheduler cosine --lr 0.01 --t_max 100 --validation_epochs 5 --num_epochs 5 --base_net_lr 0.001  --batch_size `

Error appeared after finishing the Epoch 0:

`2019-01-07 15:16:11,054 - root - INFO - Epoch: 0, Step: 2100, Average Loss: 5.7228, Average Regression Loss 3.4281, Average Classification Loss: 2.2946
2019-01-07 15:16:23,727 - root - INFO - Epoch: 0, Step: 2200, Average Loss: 5.5212, Average Regression Loss 3.2310, Average Classification Loss: 2.2902
2019-01-07 15:16:36,075 - root - INFO - Epoch: 0, Step: 2300, Average Loss: 5.7986, Average 

Regression Loss 3.5029, Average Classification Loss: 2.2956
Traceback (most recent call last):
  File "train_ssd.py", line 320, in <module>
    device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
  File "train_ssd.py", line 123, in train
    confidence, locations = net(images)
  File "/home/hoatruong/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hoatruong/pytorch-ssd/vision/ssd/ssd.py", line 81, in forward
    x = layer(x)
  File "/home/hoatruong/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hoatruong/pytorch-ssd/vision/nn/mobilenet_v2.py", line 101, in forward
    return self.conv(x)
  File "/home/hoatruong/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hoatruong/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/hoatruong/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hoatruong/anaconda3/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 67, in forward
    exponential_average_factor, self.eps)
  File "/home/hoatruong/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1346, in batch_norm
    raise ValueError('Expected more than 1 value per channel when training, got input size {}'.format(size))
ValueError: Expected more than 1 value per channel when training, got input size [1, 64, 1, 1]`

I have no problem at all with the mb1 model. Can someone help me on this problem ? Thank you in advance

**Comment by dienhoa** [comment]
Thanks. It's just a typo error in my question. I'm really sorry. But I ran with --batch_size 5  and the weird thing is I can run normally in Epoch 0. The error happened just when it come to Epoch 1

**Comment by dienhoa** [comment]
I try with this command and it works 

`python train_ssd.py --dataset_type open_images --datasets ~/data/open_images --net mb2-ssd-lite --pretrained_ssd models/mb2-ssd-lite-Epoch-1-Loss-4.739196181297302.pth --scheduler cosine --lr 0.01 --base_net_lr 0.001  --t_max 200 --validation_epochs 5 --num_epochs 2 --batch_size 8
`

I still don't know why. May be I was tired and did something stupid. I will updated if I find something new. Thanks

**Comment by dienhoa** [comment]
I don't really know. I think the error is like @zealota said that by somehow the loader just get 1 sample and can't do batchnorm. It returned to work for me by chance, I think I just copied the original code 

I created a jupyter notebook to work on this (I am more familiar with interactive coding). You find below

**Comment by thimabru1010** [comment]
Yeah, it's the batch size. When training on guns and hands dataset, you see that the last batch there isn't enough images to train, so it puts 1 image only on the batch making a tensor of shape: Image shape: torch.Size([1, 3, 300, 300]). You can simply inspect this adding this line: print(f"Image shape: {images.shape}") above [#line 122](https://github.com/qfgaohao/pytorch-ssd/blob/7174f33aa2a1540f90d827d48dea681ec1a2856c/train_ssd.py#L122), then you will see that the error shows up exactly when you have only 1 image on the batch.

OBS: I made these tests using a batch size of 4. Then I simply skipped this last image putting:
` if images.shape[0] != batch_size:
            continue`
above [#line 121](https://github.com/qfgaohao/pytorch-ssd/blob/7174f33aa2a1540f90d827d48dea681ec1a2856c/train_ssd.py#L121).

It seems to solve the problem and the training is running normally. I didn't finish my training yet, but it seems to be converging.
