### ISSUE TITLE
RuntimeError: merge_sort: failed to synchronize: an illegal memory access was encountered

### ISSUE THREAD

**Issue by seongkyun** [qfgaohao/pytorch-ssd#9]
I tried to train `vgg16-ssd` model without `base_net`.
`python3 train_ssd.py --datasets ~/data/VOC0712/VOC2007/ ~/data/VOC0712/VOC2012/ --validation_dataset ~/data/VOC0712/VOC2007/ --net vgg16-ssd --batch_size 12 --num_epochs 200 --scheduler cosine --lr 0.01 --t_max 200`
The environment is
Python 3.6(virtualenv)
Pytorch 0.4.1
CUDA 9.0
cuDNN v7.1

The whole error message is below:

>2018-10-25 15:42:22,203 - root - INFO - Namespace(balance_data=False, base_net=None, >base_net_lr=None, batch_size=12, checkpoint_folder='models/', dataset_type='voc', datasets=['/home/han/data/VOC0712/VOC2007/', '/home/han/data/VOC0712/VOC2012/'], debug_steps=100, >extra_layers_lr=None, freeze_base_net=False, freeze_net=False, gamma=0.1, lr=0.01, >milestones='80,100', momentum=0.9, net='vgg16-ssd', num_epochs=200, num_workers=4, >pretrained_ssd=None, resume=None, scheduler='cosine', t_max=200.0, use_cuda=True, >validation_dataset='/home/han/data/VOC0712/VOC2007/', validation_epochs=5, weight_decay=0.0005)
>2018-10-25 15:42:22,203 - root - INFO - Prepare training datasets.
>2018-10-25 15:42:22,206 - root - INFO - Stored labels into file models/voc-model-labels.txt.
>2018-10-25 15:42:22,206 - root - INFO - Train dataset size: 16551
>2018-10-25 15:42:22,206 - root - INFO - Prepare Validation datasets.
>2018-10-25 15:42:22,207 - root - INFO - validation dataset size: 4952
>2018-10-25 15:42:22,207 - root - INFO - Build network.
>2018-10-25 15:42:22,354 - root - INFO - Took 0.00 seconds to load the model.
>2018-10-25 15:42:23,800 - root - INFO - Learning rate: 0.01, Base net learning rate: 0.01, Extra Layers learning rate: 0.01.
>2018-10-25 15:42:23,800 - root - INFO - Uses CosineAnnealingLR scheduler.
>2018-10-25 15:42:23,800 - root - INFO - Start training from epoch 0.
>/home/han/virtualenv/py36/lib/python3.6/site-packages/torch/nn/functional.py:52: UserWarning: >size_average and reduce args will be deprecated, please use reduction='sum' instead.
>  warnings.warn(warning.format(ret))
>Traceback (most recent call last):
>  File "train_ssd.py", line 309, in <module>
>    device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
>  File "train_ssd.py", line 114, in train
>    regression_loss, classification_loss = criterion(confidence, locations, labels, boxes)  # TODO CHANGE BOXES
>  File "/home/han/virtualenv/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
>    result = self.forward(*input, **kwargs)
>  File "/home/han/study/vb_ssd_2/vision/nn/multibox_loss.py", line 38, in forward
>    mask = box_utils.hard_negative_mining(loss, labels, self.neg_pos_ratio)
>  File "/home/han/study/vb_ssd_2/vision/utils/box_utils.py", line 201, in hard_negative_mining
>    _, indexes = loss.sort(dim=1, descending=True)
>RuntimeError: merge_sort: failed to synchronize: an illegal memory access was encountered

**Comment by qfgaohao** [comment]
@seongkyun Try to use a smaller learning rate like 0.001. It can alleviate the problem. The sort method failed due to NaN numbers. It's a common problem when using this VGG net as the base net. I suspect the reason is that VGG net takes raw image data (0-255) without normalisation, the gradients are large for the first layer, causing big weights updates and loss explosion. It doesn't occur when you use mobilenet or resnet as the base net.

**Comment by seongkyun** [comment]
@qfgaohao Yup. You're right. this error is only occured with end-to-end training or other feature extractor. I'll try smaller learning rate.
